In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [2]:
url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

200

In [3]:
soup = BeautifulSoup(response.text, "html.parser")

print(soup.title.text)

    All products | Books to Scrape - Sandbox

In [4]:
books = soup.find_all("article", class_="product_pod")

print(len(books))

20

In [5]:
book = books[0]

In [6]:
title = book.h3.a["title"]

print(title)

A Light in the Attic

In [7]:
price = book.find("p", class_="price_color").text

print(price)

Â£51.77

In [8]:
rating = book.find("p", class_="star-rating")["class"][1]

print(rating)

Three

In [9]:
availability = book.find("p", class_="instock availability").text.strip()

print(availability)

In stock

In [10]:
product_url = book.h3.a["href"]

print(product_url)

catalogue/a-light-in-the-attic_1000/index.html

In [11]:
book_data = {
    "Title": book.h3.a["title"],
    "Price": book.find("p", class_="price_color").text,
    "Rating": book.find("p", class_="star-rating")["class"][1],
    "Availability": book.find("p", class_="instock availability").text.strip(),
    "URL": book.h3.a["href"]
}

print(book_data)

{'Title': 'A Light in the Attic', 'Price': 'Â£51.77', 'Rating': 'Three', 'Availability': 'In stock', 'URL': 'catalogue/a-light-in-the-attic_1000/index.html'}

In [12]:
all_books = []

for page in range(1, 51):

    url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    response = requests.get(url)

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:

        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text
        rating = book.find("p", class_="star-rating")["class"][1]
        availability = book.find(
            "p",
            class_="instock availability"
        ).text.strip()

        product_url = book.h3.a["href"]

        all_books.append({
            "Title": title,
            "Price": price,
            "Rating": rating,
            "Availability": availability,
            "URL": product_url
        })

    print(f"Page {page} completed")

    time.sleep(0.5)

Page 1 completed
Page 2 completed
Page 3 completed
Page 4 completed
Page 5 completed
Page 6 completed
Page 7 completed
Page 8 completed
Page 9 completed
Page 10 completed
Page 11 completed
Page 12 completed
Page 13 completed
Page 14 completed
Page 15 completed
Page 16 completed
Page 17 completed
Page 18 completed
Page 19 completed
Page 20 completed
Page 21 completed
Page 22 completed
Page 23 completed
Page 24 completed
Page 25 completed
Page 26 completed
Page 27 completed
Page 28 completed
Page 29 completed
Page 30 completed
Page 31 completed
Page 32 completed
Page 33 completed
Page 34 completed
Page 35 completed
Page 36 completed
Page 37 completed
Page 38 completed
Page 39 completed
Page 40 completed
Page 41 completed
Page 42 completed
Page 43 completed
Page 44 completed
Page 45 completed
Page 46 completed
Page 47 completed
Page 48 completed
Page 49 completed
Page 50 completed

In [13]:
df = pd.DataFrame(all_books)

In [14]:
df.shape

(1000, 5)

In [15]:
df.head()

,Title,Price,Rating,Availability,URL
0,A Light in the Attic,Â£51.77,Three,In stock,a-light-in-the-attic_1000/index.html
1,Tipping the Velvet,Â£53.74,One,In stock,tipping-the-velvet_999/index.html
2,Soumission,Â£50.10,One,In stock,soumission_998/index.html
3,Sharp Objects,Â£47.82,Four,In stock,sharp-objects_997/index.html
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,sapiens-a-brief-history-of-humankind_996/index...

In [16]:
df.tail()

,Title,Price,Rating,Availability,URL
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,One,In stock,alice-in-wonderland-alices-adventures-in-wonde...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,Four,In stock,ajin-demi-human-volume-1-ajin-demi-human-1_4/i...
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,Five,In stock,a-spys-devotion-the-regency-spies-of-london-1_...
998,1st to Die (Women's Murder Club #1),Â£53.98,One,In stock,1st-to-die-womens-murder-club-1_2/index.html
999,"1,000 Places to See Before You Die",Â£26.08,Five,In stock,1000-places-to-see-before-you-die_1/index.html

In [19]:
df.to_csv("books_raw.csv", index=False)